dist: trusty
sudo: false

language: node_js
node_js:
  - '10'


before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod

after_success:
  - ng deploy --branch=master --no-silent --repo=https://github.com/jien-huang/jien-huang.github.io.git --cname=www.automation-test.com
